Solve [US16] - Ajudar Solicitação #121
Lend-it/Request pull request #14
Opened 2021-03-31 23:00 UTC by Matheusafonsouza

# Solve [US16] - Ajudar Solicitação #121

## Issues

* fga-eps-mds/2020.2-Lend.it#121

## Descrição
Criação da rota para atualização do lender de um request e criação dos testes

## Tipos de mudança

Quais mudanças seu código introduz ao projeto?

- [ ] Bugfix 
- [x] Criação/Evolução de funcionalidade  
- [ ] Atualização de Documentação 

## Checklist
- [x] Lint e testes passaram localmente com minhas mudanças
- [x] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona
- [ ] Adicionei informações necessárias na documentação (se precisar)

2021-04-01 10:43 UTC, lucasdutraf requested changes

2021-04-01 10:43 UTC, lucasdutraf commented on project/api/views.py
> +from project.api.models import db
Esse import está duplicado!

2021-04-01 10:43 UTC, lucasdutraf commented on project/tests/test_request.py
> +    def test_update_lender_request(self):
Esse teste cobre somente o caso de teste de sucesso! É necessário 100% da cobertura do método para aceitarmos o pr.
![image](https://user-images.githubusercontent.com/31940073/113282849-e3028700-92bd-11eb-8e33-6b5c83ee5297.png)

2021-04-01 15:05 UTC, Matheusafonsouza commented on project/api/views.py
> +from project.api.models import db
resolvido

2021-04-01 21:54 UTC, Matheusafonsouza commented on project/tests/test_request.py
> +    def test_update_lender_request(self):
resolvido

2021-04-03 00:11 UTC, lucasdutraf approved these changes

2021-04-03 00:11 UTC, merged